"""
Django settings for binary_sets project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import dj_database_url
from configurations import Configuration, values


class Common(Configuration):
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.SecretValue()

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = values.BooleanValue(False)

    ALLOWED_HOSTS = values.ListValue([])

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django_bootstrap5",
        "django_celery_beat",
        "django_celery_results",
        "rest_framework",
        "debug_toolbar",
        "mux.apps.MuxConfig",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

    ROOT_URLCONF = "binary_sets.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [BASE_DIR / "templates"],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "binary_sets.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

    DATABASES = values.DatabaseURLValue(
        "sqlite:///{}".format(BASE_DIR.joinpath("db.sqlite3")), environ_prefix="DJANGO"
    )

    # Password validation
    # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/5.1/topics/i18n/

    LANGUAGE_CODE = values.Value("de")

    TIME_ZONE = values.Value("Europe/Berlin")

    USE_I18N = True

    LOCALE_PATHS = values.ListValue([BASE_DIR.joinpath("locale")])

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.1/howto/static-files/

    STATIC_URL = values.Value("static/")

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    CELERY_BROKER_URL = values.Value("amqp://guest:guest@localhost")
    CELERY_BEAT_SCHEDULER = values.Value(
        "django_celery_beat.schedulers:DatabaseScheduler"
    )
    CELERY_RESULT_BACKEND = values.Value("django-db")

    MEDIA_ROOT = values.PathValue(BASE_DIR.joinpath("media"), check_exists=False)

    BASE_URL = values.URLValue("http://localhost:8000")

    EMAIL = values.EmailURLValue("console://", environ_prefix="DJANGO")

    LOGIN_REDIRECT_URL = "/"
    LOGOUT_REDIRECT_URL = "/"

    BOOTSTRAP5 = {
        "color_mode": "dark",
    }

    MUX_ACCESS_TOKEN_ID = values.SecretValue()
    MUX_SECRET_KEY = values.SecretValue()


class Development(Common):
    DEBUG = values.BooleanValue(True)
    ALLOWED_HOSTS = ["*"]


class Production(Common):
    ALLOWED_HOSTS = values.ListValue(["dl.binarycollective.de"])
    BASE_URL = values.URLValue("https://dl.binarycollective.de")
    STATIC_ROOT = values.PathValue()
    DEBUG = values.BooleanValue(False)
